# Generated by Django 5.2.6 on 2025-09-28 09:52

import agents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(default=agents.models.generate_agent_code, max_length=10, unique=True)),
                ('rank', models.CharField(choices=[('Field Agent', 'Field Agent'), ('Analyst', 'Analyst'), ('Director', 'Director')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired')], default='Active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_assign_mission', 'Can assign missions to agents'), ('can_change_status', 'Can change agent status')],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mission_type', models.CharField(choices=[('Recon', 'Reconnaissance'), ('Rescue', 'Rescue Operation'), ('Surveillance', 'Surveillance'), ('Assassination', 'Assassination')], max_length=20)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Planned', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='missions', to='agents.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='assigned_missions',
            field=models.ManyToManyField(blank=True, to='agents.mission'),
        ),
    ]
