# Generated by Django 5.2.6 on 2025-09-28 10:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'permissions': [('can_assign_mission', 'Can assign missions to agents'), ('can_change_status', 'Can change agent status'), ('can_create_mission', 'Can create new missions')]},
        ),
        migrations.AddField(
            model_name='mission',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agents.mission')),
            ],
        ),
    ]
